
object Version {
    const val Kotlin = "1.8.20"
    const val River = "0.0.1-SNAPSHOT"
    const val AwsSdk = "2.18.9"
    const val Coroutine = "1.6.4"
    const val Slf4j = "1.7.36"
    const val Ktor = "2.1.3"
    const val CommonsNet = "3.8.0"
    const val Twilio = "9.1.2"
    const val Jackson = "2.14.0"
    const val Elasticsearch = "8.5.1"
    const val RabbitMQ = "5.16.0"
    const val Jms = "2.0.1"
    const val ActiveMQArtemis = "2.27.0"
    const val R2dbc = "1.0.0.RELEASE"
    const val Azure = "12.6.0"
    const val PostgreSQLJDBC = "42.5.1"
    const val MySQLJDBC = "8.0.31"
    const val Debezium = "2.0.0.Final"
    const val Groovy = "4.0.6"
    const val MongoDB = "4.8.0"
    const val ApacheFtpServer = "1.2.0"
    const val MockFtpServer = "2.7.1"
    const val Kotest = "5.5.3"
    const val Wiremock = "2.27.2"
    const val KotlinWiremock = "2.0.2"
    const val KotestWiremock = "2.0.0"
}
