name: Assembly and release

on:
  workflow_call:
    secrets:
      SIGNING_KEY_ID:
        required: true
      SIGNING_PASSWORD:
        required: true
      SIGNING_SECRET_FILE:
        required: true
      OSSRH_USER_TOKEN_USERNAME:
        required: true
      OSSRH_USER_TOKEN_PASSWORD:
        required: true

  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  test:
    name: Run all River's modules tests
    uses: ./.github/workflows/test.yml
  build:
    name: Build all monorepo
    uses: ./.github/workflows/build.yml
  release:
    name: Release all River's modules to Maven Central
    needs: [test, build]
    uses: ./.github/workflows/release.yml
    secrets:
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      SIGNING_SECRET_FILE: ${{ secrets.SIGNING_SECRET_FILE }}
      OSSRH_USER_TOKEN_USERNAME: ${{ secrets.OSSRH_USER_TOKEN_USERNAME }}
      OSSRH_USER_TOKEN_PASSWORD: ${{ secrets.OSSRH_USER_TOKEN_PASSWORD }}
