name: Assembly and release

on:
  workflow_call:
    secrets:
      JRELEASER_NEXUS2_USERNAME:
        required: true
      JRELEASER_NEXUS2_PASSWORD:
        required: true
      JRELEASER_GPG_PASSPHRASE:
        required: true
      JRELEASER_GPG_SECRET_KEY:
        required: true
      JRELEASER_GPG_PUBLIC_KEY:
        required: true

  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    needs: test
    uses: ./.github/workflows/build.yml
  release:
    uses: ./.github/workflows/release.yml
    secrets:
      JRELEASER_NEXUS2_USERNAME: ${{ secrets.JRELEASER_NEXUS2_USERNAME }}
      JRELEASER_NEXUS2_PASSWORD: ${{ secrets.JRELEASER_NEXUS2_PASSWORD }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
