name: Assembly and release

on:
  workflow_call:
    secrets:
      JRELEASER_NEXUS2_USERNAME:
        required: true
      JRELEASER_NEXUS2_PASSWORD:
        required: true
      JRELEASER_GPG_PASSPHRASE:
        required: true
      JRELEASER_GPG_SECRET_KEY:
        required: true
      JRELEASER_GPG_PUBLIC_KEY:
        required: true

  push:
    branches-ignore:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish
        uses: gradle/gradle-build-action@v2
        env:
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.JRELEASER_NEXUS2_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.JRELEASER_NEXUS2_PASSWORD }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
        with:
          arguments: jar sourcesJar javadocJar jreleaserFullRelease --no-daemon --stacktrace
