name: Assembly and release

on:
  workflow_call:
    secrets:
      SIGNING_KEY_ID:
        required: true
      SIGNING_PASSWORD:
        required: true
      SIGNING_SECRET_FILE:
        required: true
      OSSRH_USER_TOKEN_USERNAME:
        required: true
      OSSRH_USER_TOKEN_PASSWORD:
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Assembly
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assemble sourcesJar javadocJar --parallel --stacktrace

      - name: Sign & publish to Maven Central
        uses: gradle/gradle-build-action@v3
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_FILE: ${{ secrets.SIGNING_SECRET_FILE }}
          OSSRH_USER_TOKEN_USERNAME: ${{ secrets.OSSRH_USER_TOKEN_USERNAME }}
          OSSRH_USER_TOKEN_PASSWORD: ${{ secrets.OSSRH_USER_TOKEN_PASSWORD }}
        with:
          arguments: assemble sourcesJar javadocJar signAllPublications publish --stacktrace
