name: Run lint and tests

on:
  workflow_call:

  push:
    branches-ignore:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: ls -lh
    - name: Run docker-compose
      run: docker-compose up -d
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test --parallel
