name: Run lint and tests

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
      path:
        required: true
        type: string
      containers:
        required: false
        type: string
      runner:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  test:
    name: ${{ inputs.module }} module
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: ls -lh
      - name: Setup Docker [macOS only]
        if: ${{ inputs.containers && inputs.runner == 'macos-latest' }}
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: Run docker-compose [if needed]
        if: ${{ inputs.containers }}
        run: docker compose up ${{ inputs.containers }} -d
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: ${{ inputs.path }}:allTests
