name: Run lint and tests

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
      path:
        required: true
        type: string
      containers:
        required: false
        type: string

jobs:
  run:
    name: ${{ inputs.module }} module
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: ls -lh
    - name: Run docker-compose
      if: ${{ inputs.containers }}
      run: docker compose up ${{ inputs.containers }} -d
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: ${{ inputs.path }}:test
