name: Run lint and tests

on:
  workflow_call:

jobs:
  core:
    uses: ./.github/workflows/test-module.yml
    with:
      module: River Core
      path: :core

  amqp:
    uses: ./.github/workflows/test-module.yml
    with:
      module: AMQP
      path: :connector:connector-amqp
      containers: rabbitmq

  apache-kafka:
    uses: ./.github/workflows/test-module.yml
    with:
      module: Apache Kafka
      path: :connector:connector-apache:connector-apache-kafka
      containers: zookeeper kafka

  aws-lambda:
    uses: ./.github/workflows/test-module.yml
    with:
      module: AWS Lambda
      path: :connector:connector-aws:connector-aws-lambda
      containers: localstack

  aws-s3:
    uses: ./.github/workflows/test-module.yml
    with:
      module: AWS S3
      path: :connector:connector-aws:connector-aws-s3
      containers: localstack

  aws-ses:
    uses: ./.github/workflows/test-module.yml
    with:
      module: AWS SES
      path: :connector:connector-aws:connector-aws-ses
      containers: localstack

  aws-sns:
    uses: ./.github/workflows/test-module.yml
    with:
      module: AWS SNS
      path: :connector:connector-aws:connector-aws-sns
      containers: localstack

  aws-sqs:
    uses: ./.github/workflows/test-module.yml
    with:
      module: AWS SQS
      path: :connector:connector-aws:connector-aws-sqs
      containers: localstack

  azure-queue-storage:
    uses: ./.github/workflows/test-module.yml
    with:
      module: Azure Queue Storage
      path: :connector:connector-azure:connector-azure-queue-storage
      containers: azurite

  console:
    uses: ./.github/workflows/test-module.yml
    with:
      module: Console
      path: :connector:connector-console

  elasticsearch:
    uses: ./.github/workflows/test-module.yml
    with:
      module: Elasticsearch
      path: :connector:connector-elasticsearch
      containers: elasticsearch

  file:
    uses: ./.github/workflows/test-module.yml
    with:
      module: File
      path: :connector:connector-file

  format:
    uses: ./.github/workflows/test-module.yml
    with:
      module: Formats (JSON, CSV, Positional Flat Line)
      path: :connector:connector-format
      windows: true
      linux: true
      osx: true

  ftp:
    uses: ./.github/workflows/test-module.yml
    with:
      module: FTP
      path: :connector:connector-ftp

  github:
    uses: ./.github/workflows/test-module.yml
    with:
      module: GitHub
      path: :connector:connector-github

  google-drive:
    uses: ./.github/workflows/test-module.yml
    with:
      module: Google Drive
      path: :connector:connector-google:connector-google-drive

  http:
    uses: ./.github/workflows/test-module.yml
    with:
      module: http
      path: :connector:connector-http

  jms:
    uses: ./.github/workflows/test-module.yml
    with:
      module: JMS
      path: :connector:connector-jms

  mongodb:
    uses: ./.github/workflows/test-module.yml
    with:
      module: MongoDB
      path: :connector:connector-mongodb
      containers: mongodb

  openai:
    uses: ./.github/workflows/test-module.yml
    with:
      module: OpenAI
      path: :connector:connector-openai

  rdbms-jdbc:
    uses: ./.github/workflows/test-module.yml
    with:
      module: JDBC
      path: :connector:connector-rdbms:connector-rdbms-jdbc
      containers: postgresql

  rdbms-r2dbc:
    uses: ./.github/workflows/test-module.yml
    with:
      module: R2DBC
      path: :connector:connector-rdbms:connector-rdbms-r2dbc

  redhat-debezium:
    uses: ./.github/workflows/test-module.yml
    with:
      module: Debezium
      path: :connector:connector-red-hat:connector-red-hat-debezium
      containers: mysql

  redis:
    uses: ./.github/workflows/test-module.yml
    with:
      module: Redis
      path: :connector:connector-redis
      containers: redis
